### ISSUE TITLE
Failed to run example

### ISSUE THREAD

**Issue by cuonglm** [orijtech/oragent#2]
I was unable to run the quickstart guide follow https://orijtech.com/oragent

```
$ docker-compose up -d
$ docker-compose ps
        Name                      Command                  State                                                     Ports                                               
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
oragent_database_1     docker-entrypoint.sh postgres    Up             0.0.0.0:5432->5432/tcp                                                                            
oragent_oragent_1      ./ocagent --config=/etc/or ...   Up             0.0.0.0:55678->55678/tcp, 0.0.0.0:55679->55679/tcp, 0.0.0.0:8844->8844/tcp, 0.0.0.0:8877->8877/tcp
oragent_prometheus_1   /bin/prometheus --config.f ...   Exit 2                                                                                                           
oragent_zipkin_1       /bin/sh -c /zipkin/run.sh        Up (healthy)   9410/tcp, 0.0.0.0:9444->9411/tcp 
$ docker-compose logs prometheus
prometheus_1  | level=info ts=2020-09-17T07:33:27.297Z caller=main.go:293 msg="no time or size retention was set so using the default time retention" duration=15d
prometheus_1  | level=info ts=2020-09-17T07:33:27.297Z caller=main.go:329 msg="Starting Prometheus" version="(version=2.12.0, branch=HEAD, revision=43acd0e2e93f9f70c49b2267efa0124f1e759e86)"
prometheus_1  | level=info ts=2020-09-17T07:33:27.297Z caller=main.go:330 build_context="(go=go1.12.8, user=root@7a9dbdbe0cc7, date=20190818-13:53:16)"
prometheus_1  | level=info ts=2020-09-17T07:33:27.297Z caller=main.go:331 host_details="(Linux 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 df9b5ff90f65 (none))"
prometheus_1  | level=info ts=2020-09-17T07:33:27.297Z caller=main.go:332 fd_limits="(soft=1048576, hard=1048576)"
prometheus_1  | level=info ts=2020-09-17T07:33:27.297Z caller=main.go:333 vm_limits="(soft=unlimited, hard=unlimited)"
prometheus_1  | level=error ts=2020-09-17T07:33:27.297Z caller=query_logger.go:82 component=activeQueryTracker msg="Error opening query log file" file=/etc/prometheus/queries.active err="open /etc/prometheus/queries.active: permission denied"
prometheus_1  | panic: Unable to create mmap-ed active query log
prometheus_1  | 
prometheus_1  | goroutine 1 [running]:
prometheus_1  | github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffcc558fefe, 0xf, 0x14, 0x2a6b7c0, 0xc0006a1dd0, 0x2a6b7c0)
prometheus_1  | 	/app/promql/query_logger.go:112 +0x4d2
prometheus_1  | main.main()
prometheus_1  | 	/app/cmd/prometheus/main.go:361 +0x52bd
```

**Comment by odeke-em** [comment]
Looks like an issue with your Prometheus. Please comment that out and try again.

**Comment by cuonglm** [comment]
> Looks like an issue with your Prometheus. Please comment that out and try again.

Yes, comment out Prometheus section and it works. Seems due to https://github.com/prometheus/prometheus/issues/5976
